### ISSUE TITLE
Plan to support 1.0 spec?

### ISSUE THREAD

**Issue by vinjn** [cyrillef/FBX-glTF#1]
gltf 1.0 should be ready now.
It's great if this tool support the new spec.

**Comment by antont** [comment]
just for info / in case someone doesn't notice otherwise, there is a set of recent (Jan 2016) commits for 1.0 support in dev branch now: https://github.com/cyrillef/FBX-glTF/tree/dev

**Comment by pjcozzi** [comment]
@cyrillef let me know when you merge `dev` to `master`, and I will update https://github.com/KhronosGroup/glTF/blob/master/README.md to mention that this now supports glTF 1.0.

**Comment by cyrillef** [comment]
1.0 support released yesterday
I'll update the documentation early next week to describe future development

**Comment by vinjn** [comment]
Awesome!
