### ISSUE TITLE
Support for gltf 2.0?

### ISSUE THREAD

**Issue by ghost** [cyrillef/FBX-glTF#19]

**Comment by LanceMcCarthy** [comment]
I second this. Looking to convert FBX to glb for the new Windows Mixed Reality 3D app icons. [More details here](https://developer.microsoft.com/en-us/windows/mixed-reality/creating_3d_models_for_use_in_the_windows_mixed_reality_home).

**Comment by andrewvarga** [comment]
+1, gltf 2.0 support would be very useful.

**Comment by andrewharvey** [comment]
Maybe try https://github.com/facebookincubator/FBX2glTF

**Comment by ghost** [comment]
@andrewharvey That seems like the best solution.
